name: deploy demo

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: .

